[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]
version_scheme = "only-version"
local_scheme = "no-local-version"


[tool.setuptools]
include-package-data = true


[tool.setuptools.packages.find]
where = ["."]
include = ["huldra", "huldra.*"]


[project]
name = "huldra"
dynamic = ["version"]
description = "A tool to automatically fix vulnerability reports from an audit using an LLM orchestrator."
readme = "README.md"
license = "Apache-2.0"
keywords = [
    "vulnerability",
    "audit",
    "llm",
    "orchestrator",
    "security",
    "python",
    "pip-audit",
    "huldra",
    "AI",
    "tensorzero",
    "llm-orchestrator",
    "vulnerability-repair",
    "vulnerability-management",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Security",
    "Topic :: Software Development :: Quality Assurance",
]
requires-python = ">=3.11"
authors = [{ name = "Michael Owiso", email = "okwizifr@gmail.com" }]
maintainers = [{ name = "Michael Owiso", email = "okwizifr@gmail.com" }]
dependencies = ["pip-audit", "setuptools-scm"]


[project.optional-dependencies]
test = ["pytest", "pdbpp"]
ci = ["tox-uv"]
dev = ["ruff", "pyrefly"]


[project.scripts]
huldra-cli = "huldra.cli:main"


[tool.ruff]
exclude = [
    ".eggs",
    ".git",
    ".nox",
    ".pytype",
    ".ruff_cache",
    ".tox",
    ".venv",
    "__pycache__",
    "__pypackages__",
    "_build",
    "build",
    "dist",
    "docs",
    "venv",
    ".pytest_cache",
    "env",
]
line-length = 79
target-version = "py311"


[tool.ruff.lint]
extend-select = [
    # flake8-comprehensions
    "C4",

    # flake8-simplify
    "SIM",

    # flake8-debugger
    "T10",

    # flake8-print
    "T20",

    # flake8-bugbear
    "B",

    # isort
    "I",

    # pycodestyle
    "E",

    # flake8-warnings
    "W",

    # Pyflakes
    "F",

    # missing docstrings
    "D1",

    # docstrings style (multi-line-summary-first-line)
    "D212",

    # type hints and checks
    "ANN",
]
fixable = ["ALL"]
per-file-ignores = { "tests/*.py" = ["ANN201", "ANN001"] }
pydocstyle = { convention = "google" }
mccabe = { max-complexity = 10 }


[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true


[tool.pyrefly]
project-includes = ["huldra"]
project-excludes = ["**/.[!/.]*", "**/tests"]
search-path = ["huldra"]
