[tox]
requires =
    tox-uv
env_list = lint, test, package, publish


[testenv]
basepython = 
    python3.13
whitelist_externals = sh
allowlist_externals = make, coverage, uv
uv_system_site_packages = true
use_uv = true


[testenv:lint]
description = checks linters and types
depends = testenv
deps =
  .[dev]
commands =
    make lint
    make type_check


[testenv:test]
description = runs tests
depends = testenv
deps =
  .[test]
commands =
    coverage erase
    make test


[testenv:package]
description = build the library
passenv =
    SETUPTOOLS_SCM_PRETEND_VERSION

commands =
    uv build --no-build-isolation .
depends = testenv
deps =
    uv
    setuptools
    setuptools_scm
skip_install = true


[testenv:publish]
passenv = 
    UV_PUBLISH_USERNAME
    UV_PUBLISH_PASSWORD
commands =
    uv publish
depends = package
description = publish to PyPI
skip_install = true
